services:
  - type: web
    name: davvvat-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        value: your-mysql-host
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: your-mysql-user
      - key: DB_PASSWORD
        value: your-mysql-password
      - key: DB_NAME
        value: DavvvatDB
      - key: ALLOWED_ORIGIN
        value: https://sotheso.github.io
